#
# Makefile for touch panel driver
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_VIRTUAL)	+= virtual_tp.o
obj-$(CONFIG_TOUCHPANEL_IT7236)        	+= ite7236_tp.o
obj-$(CONFIG_TOUCHPANEL_CP2615)        	+= cp2615.o
obj-$(CONFIG_TOUCHPANEL_CP2615_PDMA)   	+= cp2615_pdma.o
obj-$(CONFIG_TOUCHPANEL_SP948T)		+= sp948t_i2c.o
obj-$(CONFIG_TOUCHPANEL_ZET6231)	+= zet6231.o
obj-$(CONFIG_TOUCHPANEL_FT3X07)		+= ft3x07.o
obj-$(CONFIG_TOUCHPANEL_IT7236_KEY)	+= ite7236_key.o