snd-soc-jz-aic-core-objs := jz-aic.o
snd-soc-jz-aic-dma-objs := jz-aic-dma.o
snd-soc-jz-spdif-objs := jz-spdif.o

obj-$(CONFIG_SND_JZ_SOC_AIC_CORE) += snd-soc-jz-aic-core.o
obj-$(CONFIG_SND_JZ_SOC_AIC_DMA) += snd-soc-jz-aic-dma.o
obj-$(CONFIG_SND_JZ_SOC_SPDIF) += snd-soc-jz-spdif.o

snd-soc-mensa-spdif-objs := mensa_spdif.o

obj-$(CONFIG_SND_JZ_SOC_MENSA_SPDIF) += snd-soc-mensa-spdif.o
