
obj-$(CONFIG_LCD_VIRTUAL) += lcd-virtual.o
obj-$(CONFIG_LCD_VIRTUAL_800480) += lcd-virtual-800480.o
obj-$(CONFIG_LCD_ECX336AF) += lcd-ecx336af.o
obj-$(CONFIG_LCD_HIMAX7033) += lcd-himax7033.o
obj-$(CONFIG_LCD_HIMAX7097) += lcd-himax7097.o
obj-$(CONFIG_LCD_HIMAX7069) += lcd-himax7069.o
obj-$(CONFIG_LCD_ILI9342C) += lcd-ili9342c.o
obj-$(CONFIG_OLED_SSD1306) += ssd1306.o